// Star database for Vietnamese Ziwei Doushu
import { SaoData } from './types';

export const CS_DATA: SaoData[] = [
  { id: 1, ten: 'Tử vi', hanh: 5, dac: '28', ham: '-', mieu: '6739', vuong: '5b', binh: 'c14a', bacDT: true, catTinh: true },
  { id: 2, ten: 'Liêm trinh', hanh: 4, dac: '28', ham: '6c4a', mieu: '5b', vuong: '1739', binh: '', bacDT: true, catTinh: true },
  { id: 3, ten: 'Thiên đồng', hanh: 2, dac: '46c', ham: '5a287b', mieu: '39', vuong: '1', binh: '', bacDT: false, catTinh: true },
  { id: 4, ten: 'Vũ khúc', hanh: 1, dac: '4a', ham: '6c', mieu: '5b28', vuong: '3917', binh: '', bacDT: true, catTinh: true },
  { id: 5, ten: 'Thái dương', hanh: 4, dac: '28', ham: '9abc1', mieu: '67', vuong: '345', binh: '', bacDT: false, catTinh: true },
  { id: 6, ten: 'Thiên cơ', hanh: 3, dac: '1728', ham: '3c', mieu: '5b4a', vuong: '69', binh: '', bacDT: false, catTinh: true },
  { id: 7, ten: 'Thiên phủ', hanh: 5, dac: '6c8', ham: '-', mieu: '3917', vuong: '5b', binh: '4a2', bacDT: false, catTinh: true },
  { id: 8, ten: 'Thái âm', hanh: 2, dac: '28', ham: '34567', mieu: 'abc', vuong: '91', binh: '', bacDT: true, catTinh: true },
  { id: 9, ten: 'Tham lang', hanh: 2, dac: '39', ham: '6c174a', mieu: '28', vuong: '5b', binh: '', bacDT: true, catTinh: true },
  { id: 10, ten: 'Cự môn', hanh: 2, dac: '9c', ham: '5b286', mieu: '4a', vuong: '173', binh: '', bacDT: true, catTinh: true },
  { id: 11, ten: 'Thiên tướng', hanh: 2, dac: '286c', ham: '4a', mieu: '39', vuong: '5b17', binh: '', bacDT: false, catTinh: true },
  { id: 12, ten: 'Thiên lương', hanh: 3, dac: '28', ham: 'a6c', mieu: '75b', vuong: '1439', binh: '', bacDT: false, catTinh: true },
  { id: 13, ten: 'Thất sát', hanh: 1, dac: '28', ham: '4a5b', mieu: '3917', vuong: '6c', binh: '', bacDT: false, catTinh: true },
  { id: 14, ten: 'Phá quân', hanh: 2, dac: '5b', ham: '4a396c', mieu: '17', vuong: '28', binh: '', bacDT: true, catTinh: true },
  { id: 15, ten: 'Thái tuế', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 16, ten: 'Thiếu dương', hanh: 4, dac: '34567', ham: '1289abc', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 17, ten: 'Tang môn', hanh: 3, dac: '394a', ham: '125678bc', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 18, ten: 'Thiếu âm', hanh: 2, dac: '9abc1', ham: '2345678', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 19, ten: 'Quan phù', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 20, ten: 'Tử phù', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 21, ten: 'Tuế phá', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 22, ten: 'Long đức', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 23, ten: 'Bạch hổ', hanh: 1, dac: '394a', ham: '125678bc', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 24, ten: 'Phúc đức', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 25, ten: 'Điếu khách', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 26, ten: 'Trực phù', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 27, ten: 'Lộc tồn', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 28, ten: 'Lực sĩ', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 29, ten: 'Thanh long', hanh: 2, dac: '5b28c1', ham: '34679ab', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 30, ten: 'Tiểu hao', hanh: 4, dac: '34a9', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 31, ten: 'Tướng quân', hanh: 3, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 32, ten: 'Tấu thư', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 33, ten: 'Phi liêm', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 34, ten: 'Hỉ thần', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 35, ten: 'Bệnh phù', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 36, ten: 'Đại hao', hanh: 4, dac: '34a9', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 37, ten: 'Phục binh', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 38, ten: 'Quan phủ', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 39, ten: 'Tràng sinh', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 40, ten: 'Mộc dục', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 41, ten: 'Quan đới', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 42, ten: 'Lâm quan', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 43, ten: 'Đế vượng', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 44, ten: 'Suy', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 45, ten: 'Bệnh', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 46, ten: 'Tử', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 47, ten: 'Mộ', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 48, ten: 'Tuyệt', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 49, ten: 'Thai', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 50, ten: 'Dưỡng', hanh: 3, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 51, ten: 'Đà la', hanh: 1, dac: '5b286a', ham: '134579bc', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 52, ten: 'Kình dương', hanh: 1, dac: '5b28', ham: '134679ac', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 53, ten: 'Địa không', hanh: 4, dac: '6c39', ham: '124578ab', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 54, ten: 'Địa kiếp', hanh: 4, dac: '6c39', ham: '124578ab', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 55, ten: 'Linh tinh', hanh: 4, dac: '34567', ham: '1289abc', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 56, ten: 'Hỏa tinh', hanh: 4, dac: '34567', ham: '1289abc', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 57, ten: 'Văn xương', hanh: 1, dac: '5b286c', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 58, ten: 'Văn khúc', hanh: 2, dac: '5b286c', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 59, ten: 'Thiên khôi', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 60, ten: 'Thiên việt', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 61, ten: 'Tả phù', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 62, ten: 'Hữu bật', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 63, ten: 'Long trì', hanh: 2, dac: '4a', ham: '_', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 64, ten: 'Phượng các', hanh: 5, dac: '4a', ham: '_', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 65, ten: 'Tam thai', hanh: 3, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 66, ten: 'Bát tọa', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 67, ten: 'Ân quang', hanh: 3, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 68, ten: 'Thiên quý', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 69, ten: 'Thiên khốc', hanh: 2, dac: '17', ham: '_', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 70, ten: 'Thiên hư', hanh: 2, dac: '17', ham: '_', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 71, ten: 'Thiên đức', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 72, ten: 'Nguyệt đức', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 73, ten: 'Thiên hình', hanh: 4, dac: '394a', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 74, ten: 'Thiên riêu', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 75, ten: 'Thiên y', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 76, ten: 'Quốc ấn', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 77, ten: 'Đường phù', hanh: 3, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 78, ten: 'Đào hoa', hanh: 3, dac: '14', ham: '_', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 79, ten: 'Hồng loan', hanh: 2, dac: '14579', ham: '-', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 80, ten: 'Thiên hỉ', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 81, ten: 'Thiên giải', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 82, ten: 'Địa giải', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 83, ten: 'Giải thần', hanh: 3, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 84, ten: 'Thai phụ', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 85, ten: 'Phong cáo', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 86, ten: 'Thiên tài', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 87, ten: 'Thiên thọ', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 88, ten: 'Thiên thương', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 89, ten: 'Thiên sứ', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 90, ten: 'Thiên la', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 91, ten: 'Địa võng', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 92, ten: 'Hóa khoa', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 93, ten: 'Hóa quyền', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 94, ten: 'Hóa lộc', hanh: 3, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 95, ten: 'Hóa kỵ', hanh: 2, dac: '5b28', ham: '_', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 96, ten: 'Cô thần', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 97, ten: 'Quả tú', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 98, ten: 'Thiên mã', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 99, ten: 'Phá toái', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 100, ten: 'Thiên quan', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 101, ten: 'Thiên phúc', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 102, ten: 'Lưu hà', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 103, ten: 'Thiên trù', hanh: 5, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 104, ten: 'Kiếp sát', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 105, ten: 'Hoa cái', hanh: 1, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 106, ten: 'Văn tinh', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 107, ten: 'Đẩu quân', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 108, ten: 'Thiên Không', hanh: 4, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 109, ten: 'Bác sĩ', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: true },
  { id: 110, ten: 'Tuần', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
  { id: 111, ten: 'Triệt', hanh: 2, dac: '', ham: '', mieu: '', vuong: '', binh: '', bacDT: false, catTinh: false },
];

export const D_CHI = ['Tí', 'Sữu', 'Dần', 'Mão', 'Thìn', 'Tị', 'Ngọ', 'Mùi', 'Thân', 'Dậu', 'Tuất', 'Hợi'];
export const T_CAN = ['Giáp', 'Ất', 'Bính', 'Đinh', 'Mậu', 'Kỹ', 'Canh', 'Tân', 'Nhâm', 'Quí'];
export const LUC_THAN = ['Mệnh', 'Phụ mẫu', 'Phúc đức', 'Điền trạch', 'Quan lộc', 'Nô bộc', 'Di', 'Tật ách', 'Tài bạch', 'Tử tức', 'Phu thê', 'Huynh đệ'];
